// <auto-generated />
using System;
using Basket.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basket.Persistence.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    [Migration("20241024121525_AddCatalogItemName")]
    partial class AddCatalogItemName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Basket.Models.DomainModels.UserBasket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BasketType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserBaskets", (string)null);

                    b.HasDiscriminator<string>("BasketType").HasValue("UserBasket");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Basket.Models.DomainModels.PrimaryUserBasket", b =>
                {
                    b.HasBaseType("Basket.Models.DomainModels.UserBasket");

                    b.HasDiscriminator().HasValue("Primary");
                });

            modelBuilder.Entity("Basket.Models.DomainModels.SecondaryUserBasket", b =>
                {
                    b.HasBaseType("Basket.Models.DomainModels.UserBasket");

                    b.HasDiscriminator().HasValue("Secondary");
                });

            modelBuilder.Entity("Basket.Models.DomainModels.UserBasket", b =>
                {
                    b.OwnsMany("Basket.Models.DomainModels.BasketCatalogItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CatalogItemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal?>("LatestPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(false)
                                .HasColumnType("varchar(100)");

                            b1.Property<int>("UserBasketId")
                                .HasColumnType("int");

                            b1.Property<bool>("UserChangedSeen")
                                .HasColumnType("bit");

                            b1.HasKey("Id");

                            b1.HasIndex("UserBasketId");

                            b1.ToTable("BasketCatalogItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserBasketId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
